# Generated by Django 5.0.6 on 2024-06-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="total_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
