# Generated by Django 5.0.6 on 2024-06-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_enrollment_total_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="folder_prefix",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
