# Generated by Django 5.0.6 on 2024-06-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_course_enrollment_code_course_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="total_minutes_trip_a",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
