# Generated by Django 5.0.6 on 2024-06-11 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_enrollment_total_minutes_trip_a"),
    ]

    operations = [
        migrations.CreateModel(
            name="Screenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screenshot", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("at_minute", models.PositiveIntegerField(default=0)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.enrollment"
                    ),
                ),
                (
                    "enrollment_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.enrollmentday",
                    ),
                ),
            ],
        ),
    ]
