# Generated by Django 5.0.6 on 2024-06-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_screenshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="total_ban_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="enrollmentday",
            name="ban_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
