# Generated by Django 5.0.6 on 2024-06-29 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_enrollment_total_ban_minutes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="screenshot",
            name="enrollment_day",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="total_minutes_trip_a",
        ),
        migrations.CreateModel(
            name="EnrollmentTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minutes", models.PositiveIntegerField(default=0)),
                ("last_submission", models.DateTimeField(blank=True, null=True)),
                ("ban_minutes", models.PositiveIntegerField(default=0)),
                ("marked_as_done", models.BooleanField(default=False)),
                ("accepted", models.BooleanField(default=False)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.enrollment"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="screenshot",
            name="enrollment_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.enrollmenttask",
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("text", models.TextField()),
                ("minimum_minutes", models.PositiveIntegerField(default=0)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.course"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="enrollmenttask",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.task"
            ),
        ),
        migrations.DeleteModel(
            name="EnrollmentDay",
        ),
    ]
