# Generated by Django 5.0.6 on 2024-07-02 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_screenshot_enrollment_day_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="enrollmenttask",
            name="score",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="task",
            name="allow_finish_earlier",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="require_attachments",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attachment", models.FileField(upload_to="attachments/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.enrollmenttask",
                    ),
                ),
            ],
        ),
    ]
