# Generated by Django 5.0.6 on 2024-07-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_task_options_enrollmenttask_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="screenshot_interval_minutes",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
