# Generated by Django 5.0.6 on 2024-07-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_course_screenshot_interval_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmenttask',
            name='under_review',
            field=models.BooleanField(blank=True, default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='enrollmenttask',
            name='marked_as_done',
            field=models.BooleanField(blank=True, default=False, max_length=100),
        ),
    ]
