# Generated by Django 5.0.6 on 2024-07-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_enrollmenttask_under_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='comment_text',
            field=models.CharField(blank=True, max_length=2000, null=''),
        ),
    ]
