# Generated by Django 5.0.6 on 2024-08-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_attachment_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='screenshot',
            field=models.URLField(),
        ),
    ]
