# Generated by Django 5.0.6 on 2024-08-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_attachment_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmenttask',
            name='last_shared_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
