# Generated by Django 5.0.6 on 2024-08-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_enrollmenttask_last_shared_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenshot",
            name="sent_to_s3",
            field=models.BooleanField(default=False),
        ),
    ]
