# Generated by Django 5.0.6 on 2024-08-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_screenshot_sent_to_s3"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenshot",
            name="s3_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
