# Generated by Django 5.0.6 on 2024-09-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_screenshot_s3_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="color",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
