# Generated by Django 5.0.6 on 2024-09-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_course_color_course_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
