# Generated by Django 5.0.6 on 2024-09-05 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_enrollment_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.task",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="enrollment_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.enrollmenttask",
            ),
        ),
    ]
