# Generated by Django 5.0.6 on 2024-09-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_attachment_task_alter_attachment_enrollment_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="sent_to_s3",
            field=models.BooleanField(default=False),
        ),
    ]
