# Generated by Django 5.0.6 on 2024-09-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_attachment_sent_to_s3"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="s3_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
