# Generated by Django 5.0.6 on 2024-09-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_attachment_s3_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="enrollment_code",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
