# Generated by Django 5.0.6 on 2024-09-14 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_alter_course_options_forgotpassword_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="copy_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.task",
            ),
        ),
    ]
