# Generated by Django 5.0.6 on 2024-09-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_task_copy_of"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="screenshot",
            options={"ordering": ["id"]},
        ),
    ]
