# Generated by Django 5.0.6 on 2024-09-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_alter_screenshot_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="s3_key",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
