# Generated by Django 5.0.6 on 2024-09-17 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_alter_attachment_s3_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="comment_text",
        ),
        migrations.AddField(
            model_name="task",
            name="available_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="available_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="EnrollmentTaskMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=10000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("from_student", models.BooleanField(default=False)),
                (
                    "enrollment_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.enrollmenttask",
                    ),
                ),
            ],
        ),
    ]
