# Generated by Django 5.0.6 on 2024-10-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_remove_attachment_comment_text_task_available_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmenttask",
            name="watched",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="screenshot",
            name="s3_key",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="screenshot",
            name="screenshot",
            field=models.URLField(max_length=1000),
        ),
    ]
