# Generated by Django 5.0.6 on 2024-10-19 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_enrollmenttask_watched_alter_screenshot_s3_key_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollmenttask",
            options={"ordering": ["id"]},
        ),
    ]
