# Generated by Django 5.0.6 on 2024-10-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_alter_enrollmenttask_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmenttask",
            name="note",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
