# Generated by Django 5.0.6 on 2024-12-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_enrollmenttask_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmenttask",
            name="last_hh_mm",
            field=models.CharField(default="00:00", max_length=10),
        ),
    ]
