# Generated by Django 5.0.6 on 2025-02-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_alter_course_department_alter_course_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmenttask",
            name="ai_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="enrollmenttask",
            name="ai_ready",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="enrollmenttask",
            name="marked_as_done",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="enrollmenttask",
            name="under_review",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
