# Generated by Django 5.0.6 on 2025-02-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_enrollmenttask_ai_note_enrollmenttask_ai_ready_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenshot",
            name="ai_comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="screenshot",
            name="ai_ready",
            field=models.BooleanField(default=False),
        ),
    ]
