# Generated by Django 5.0.6 on 2025-02-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_screenshot_ai_comment_screenshot_ai_ready"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmenttask",
            name="ai_request",
            field=models.BooleanField(default=False),
        ),
    ]
