# Generated by Django 5.0.6 on 2025-02-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_enrollmenttask_ai_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="ai_screenshots_count",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
