# Generated by Django 5.0.6 on 2025-02-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_task_ai_screenshots_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmenttask",
            name="ai_score",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
