# Generated by Django 5.0.6 on 2025-02-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_enrollmenttask_ai_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmenttask",
            name="ai_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
