# Generated by Django 5.0.6 on 2025-02-13 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_enrollmenttask_ai_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentTaskAiDialog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("from_student", models.BooleanField(default=False)),
                ("from_teacher", models.BooleanField(default=False)),
                ("from_ai", models.BooleanField(default=False)),
                (
                    "enrollment_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.enrollmenttask",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
