# Generated by Django 5.0.6 on 2025-02-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_enrollmenttaskaidialog"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollmenttask",
            name="ai_used_screenshots",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
