# Generated by Django 5.0.6 on 2025-03-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
