#!/bin/bash

NAME="oqulabs"                                  # Name of the application
DJANGODIR=/var/www/oqulabs
SOCKFILE=/var/www/oqulabs/oqulabs.sock  # we will communicte using this unix socket
USER=root                                        # the user to run as
GROUP=www-data                                     # the group to run as
NUM_WORKERS=7                                     # how many worker processes should Gunicorn spawn
TIMEOUT=600
DJANGO_SETTINGS_MODULE=sms.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=sms.wsgi                     # WSGI module name


echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source ./venv/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec ./venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --timeout $TIMEOUT \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-

